# nucleo/dicionario.py

DICIONARIO = {
    # Pronomes e verbos
    "eu": "I",
    "preciso": "need",
    "estudar": "study",
    "gosto": "like",
    "programar": "program",
    "vou": "will",
    "revisar": "review",
    "quero": "want",
    "aprender": "learn",
    "organizar": "organize",
    "estou": "am",
    "lendo": "reading",
    "entender": "understand",
    "participei": "attended",
    "melhorar": "improve",
    "preparando": "preparing",
    "analisar": "analyze",
    "enviar": "send",
    "estudando": "studying",
    "aprendendo": "learning",
    "interpretar": "interpret",
    "fazendo": "doing",
    "traduzir": "translate",
    "ler": "read",
    
    # Artigos, preposições e conectores
    "um": "a",
    "uma": "a",
    "o": "the",
    "a": "the",
    "os": "the",
    "as": "the",
    "de": "of",
    "do": "of the",
    "da": "of the",
    "para": "for",
    "antes": "before",
    "em": "in/on",
    "sobre": "about",
    "e": "and",
    
    # Substantivos e objetos
    "banco": "database",
    "dados": "data",
    "prova": "exam",
    "materia": "subject",
    "ingles": "English",
    "instrumental": "technical",
    "tempo": "time",
    "estudo": "study",
    "artigo": "article",
    "cientifico": "scientific",
    "importante": "important",
    "manual": "manual",
    "tecnico": "technical",
    "sistema": "system",
    "reuniao": "meeting",
    "online": "online",
    "ontem": "yesterday",
    "escrita": "writing",
    "academica": "academic",
    "apresentacao": "presentation",
    "relatorio": "report",
    "email": "email",
    "algoritmos": "algorithms",
    "estruturas": "structures",
    "codigo": "code",
    "projeto": "project",
    "vocabulario": "vocabulary",
    "inteligencia": "intelligence",
    "artificial": "artificial",
    "graficos": "charts",
    "tabelas": "tables",
    "curso": "course",
    "texto": "text",
    "internacionais": "international",
    "dias": "days",
}
